name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          python3-dev \
          autoconf \
          automake \
          libtool \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good

    - name: Set up Android SDK
      run: |
        # Using a known version of command-line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmd-tools.zip
        mkdir -p android-sdk/cmdline-tools
        unzip -q cmd-tools.zip -d android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        rm cmd-tools.zip
        
        # Set environment variables for this step and subsequent steps
        export ANDROID_HOME=$GITHUB_WORKSPACE/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

        # Accept licenses and install SDK components
        yes | sdkmanager --licenses > /dev/null
        sdkmanager "platforms;android-31" "build-tools;31.0.0" "platform-tools"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython buildozer
        pip install kivy numpy pillow matplotlib tensorflow
    
    - name: Build APK
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: handwriting-recognition-apk
        path: bin/*.apk
